'use client';
import {useEffect,useState} from 'react';
const tracks=[
 {topic:'HTML',label:'Criar páginas',description:'Títulos, parágrafos e links.',note:'Comece por aqui se nunca criou um site.'},
 {topic:'CSS',label:'Estilizar páginas',description:'Cores, fontes e espaçamento.',note:'Recomendado depois de HTML.'},
 {topic:'JavaScript',label:'Programar para a web',description:'Variáveis, condições, arrays e eventos.',note:'Use o navegador para testar o código.'},
 {topic:'Python',label:'Lógica e funções',description:'Variáveis, listas, condições e repetição.',note:'Exercícios com conferência de sintaxe e requisitos.'},
 {topic:'Java',label:'Tipos e métodos',description:'Programa principal, arrays, laços e métodos.',note:'Exercícios com conferência de sintaxe e requisitos.'},
 {topic:'C#',label:'Programar em C#',description:'Tipos, condições, arrays e funções.',note:'Exercícios com conferência de requisitos.'},
];
export default function LearningView(p){
 const {lessons,current,completed,track,stage,user,loadingAccount,busy,answering,accountError,saveStatus,accountReady,correctAnswer,choice,feedback,code,documentHtml,runCount,codeReview,reviewing}=p;
 const [selected,setSelected]=useState(null);
 useEffect(()=>setSelected(null),[current,track]);
 const lesson=lessons[current],indices=lessons.flatMap((item,index)=>item.topic===track?[index]:[]),position=indices.indexOf(current);
 const disabled=busy||loadingAccount||answering||reviewing;
 const next=indices[position+1];
 return <div className="flow"><header className="flow-header"><button className="flow-brand" onClick={p.home} disabled={disabled}><span>&lt;/&gt;</span> Code & Words</button><div className="header-account">{user?<><span className="account-name">{user.name}</span><button className="account-button" onClick={p.logout} disabled={disabled}>Sair</button></>:<button className="account-button" disabled={loadingAccount} onClick={p.showAccount}>Entrar / Criar conta</button>}</div></header><main className={track?'lesson-flow':'track-flow'}>
 {accountError&&<p className="account-error" role="alert">{accountError}</p>}
 {!track?<><div className="home-heading"><div><p className="flow-label">CURSOS</p><h1>O que você quer aprender?</h1><p>Escolha uma linguagem ou tecnologia. Aprenda o inglês usado no código em cada aula.</p></div>{user&&accountReady&&<button className="primary" onClick={()=>p.open(current)} disabled={disabled}>Continuar última aula</button>}</div><div className="track-list">{tracks.map(item=>{const rows=lessons.flatMap((lesson,index)=>lesson.topic===item.topic?[index]:[]);const count=rows.filter(index=>completed.includes(index)).length;return <article className={'track-card track-'+(item.topic==='C#'?'csharp':item.topic.toLowerCase())} key={item.topic}><div className="track-meta"><span>FUNDAMENTOS E PRÁTICA</span><span>{rows.length} aulas</span></div><h2>{item.topic}</h2><h3>{item.label}</h3><p>{item.description}</p><small>{item.note}</small><div className="track-bottom"><span>{count} de {rows.length} concluídas</span><button className="primary" onClick={()=>p.selectTrack(item.topic)} disabled={disabled}>{count?'Continuar':'Começar'}</button></div></article>;})}</div><section className="how-lessons"><h2>Como funciona uma aula</h2><ol><li><b>Estudar</b><span>Leia o conceito e as palavras em inglês.</span></li><li><b>Praticar</b><span>Altere o código e veja o resultado.</span></li><li><b>Responder</b><span>Confira o que aprendeu e avance.</span></li></ol></section>{!user&&<p className="guest-note">Você pode estudar sem cadastro. Para guardar o progresso, crie uma conta.</p>}</>:<><div className="lesson-top"><button className="text-button" disabled={disabled} onClick={p.home}>Voltar às trilhas</button><span>{track} · {lesson.level} · Aula {position+1} de {indices.length}</span></div><nav className="stage-nav" aria-label="Etapas da aula">{[['study','Estudar'],['practice','Praticar'],['quiz','Responder']].map(([id,label],index)=><button key={id} disabled={disabled} aria-current={stage===id?'step':undefined} onClick={()=>p.setStage(id)}><span>{index+1}</span>{label}</button>)}</nav><h1 className="flow-title">{lesson.title}</h1>
 {stage==='study'&&<><section className="study-content"><h2>Conceito</h2><p>{lesson.text}</p></section><section className="lesson-vocabulary"><h2>Inglês desta aula</h2><table><thead><tr><th>Inglês</th><th>Português</th></tr></thead><tbody>{lesson.words.map(([en,pt])=><tr key={en}><td lang="en">{en}</td><td>{pt}</td></tr>)}</tbody></table></section><div className="stage-actions"><button className="primary" onClick={()=>p.setStage('practice')}>Ir para a prática</button></div></>}
 {stage==='practice'&&<><p className="practice-task" id="instruction">{lesson.instruction}</p><div className="workbench"><div className="code-panel"><div className="panel-bar"><label htmlFor="editor">{lesson.filename}</label><button onClick={p.reset} disabled={disabled}>Restaurar exemplo</button></div><textarea id="editor" aria-describedby="instruction" spellCheck="false" autoCapitalize="off" maxLength={16384} disabled={disabled||(user&&!accountReady)} value={code} onChange={event=>p.changeCode(event.target.value)}/><div className="editor-footer"><span>{lesson.topic}</span><button className="primary" disabled={disabled} onClick={lesson.checks?p.checkCode:p.run}>{lesson.checks?(reviewing?'Conferindo…':'Conferir código'):'Executar código'}</button></div></div><div className="result-panel"><div className="result-bar">{lesson.checks?'CONFERÊNCIA DO EXERCÍCIO':'RESULTADO'}</div>{lesson.checks?<div className="code-check" aria-live="polite"><p>{codeReview?.feedback||'Edite o exemplo e clique em Conferir código.'}</p>{codeReview?.errors?.length>0&&<ul>{codeReview.errors.map((error,index)=><li key={index}>{error.line?'Linha '+error.line+': ':''}{error.message}</li>)}</ul>}<small>{lesson.topic==='C#'?'Esta checagem verifica estrutura e requisitos do exercício.':'Esta checagem verifica sintaxe e requisitos do exercício.'} Não compila nem executa o programa.</small></div>:<iframe key={runCount+'-'+current} title="Resultado do código" sandbox="allow-scripts" srcDoc={documentHtml}/>}</div></div><div className="save-row"><span role="status">{user?saveStatus:'Código temporário. Entre na sua conta para salvar.'}</span>{user&&<button className="text-button" onClick={p.save} disabled={disabled}>Salvar código</button>}</div><div className="stage-actions"><button className="text-button" onClick={()=>p.setStage('study')}>Voltar ao conceito</button><button className="primary" onClick={()=>p.setStage('quiz')}>Responder questão</button></div></>}
 {stage==='quiz'&&<section className="question-flow"><p className="question-type">{lesson.kind==='sum'?'SOMATÓRIA · MAIS DE UMA AFIRMAÇÃO':lesson.kind==='descriptive'?'RESPOSTA CURTA':'MÚLTIPLA ESCOLHA · UMA RESPOSTA'}</p><h2>{lesson.question}</h2>
 {lesson.kind==='descriptive'?<div className="descriptive-answer"><label htmlFor="written-answer">Sua resposta em português</label><textarea id="written-answer" value={typeof selected==='string'?selected:''} onChange={event=>setSelected(event.target.value)} maxLength={800} disabled={disabled||correctAnswer}/><small>De 8 a 800 caracteres. A correção procura estes critérios:</small><ul>{lesson.criteria.map(item=><li key={item.label}>{item.label}</li>)}</ul></div>:<fieldset disabled={disabled||correctAnswer}><legend>{lesson.kind==='sum'?'Selecione todas as afirmações corretas':'Selecione uma alternativa'}</legend>{lesson.answers.map((item,index)=>{const value=lesson.kind==='sum'?lesson.values[index]:index;const checked=lesson.kind==='sum'?Array.isArray(selected)&&selected.includes(value):selected===index;return <label key={item} className={checked?'selected-option':''}><input type={lesson.kind==='sum'?'checkbox':'radio'} name="answer" value={value} checked={checked} onChange={()=>lesson.kind==='sum'?setSelected(previous=>{const values=Array.isArray(previous)?previous:[];return values.includes(value)?values.filter(item=>item!==value):[...values,value];}):setSelected(index)}/><span>{item}</span></label>;})}</fieldset>}
 {lesson.kind==='sum'&&<p className="sum-total">Somatória selecionada: {Array.isArray(selected)?selected.reduce((sum,value)=>sum+value,0):0}</p>}
 {!correctAnswer&&<button className="primary" disabled={disabled||selected===null||(Array.isArray(selected)&&!selected.length)||(typeof selected==='string'&&selected.trim().length<8)} onClick={()=>p.answer(selected)}>{answering?'Conferindo…':'Conferir resposta'}</button>}<p className={'feedback '+(correctAnswer?'correct':'')} role="status">{feedback}</p>{correctAnswer&&<div className="stage-actions"><span>{next===undefined?'Você concluiu esta trilha.':'Aula concluída.'}</span><button className="primary" onClick={()=>next===undefined?p.home():p.open(next)}>{next===undefined?'Escolher outra trilha':'Próxima aula'}</button></div>}<button className="text-button review-link" onClick={()=>p.setStage('study')}>Rever explicação</button></section>}

 <div className="lesson-account-note">{user?(accountReady?'Progresso vinculado à sua conta.':'Recuperando dados da conta…'):'Sem conta: seu progresso será perdido ao fechar a página.'}</div></>}
 </main></div>;
}
