import {additionalLessons} from './additional-lessons.js';
const lessonIds = ['html-hello', 'html-links', 'css-colors', 'css-spacing', 'js-events', 'js-counter'];
const baseLessons = [
  {topic:'HTML',title:'Olá, mundo!',summary:'Sua primeira página',text:'HTML organiza o conteúdo de uma página. A tag <h1> marca o título principal; a tag <p> marca um parágrafo. Tags de fechamento usam uma barra: </p>.',words:[['hello','olá'],['world','mundo'],['heading','título']],instruction:'Troque “Hello, world!” por uma saudação sua em inglês, como “Hello, Ana!”. Depois, execute o código.',code:'<h1>Hello, world!</h1>\n<p>This is my first website.</p>',question:'O que “Hello, world!” significa?',answers:['Olá, mundo!','Meu primeiro site','Até amanhã!'],correct:0,feedback:'Isso! Hello = olá e world = mundo. Você também criou um título com <h1>.'},
  {topic:'HTML',title:'Palavras que viram links',summary:'Parágrafos e links',text:'Um link conecta uma página a outra. A tag <a> cria o link e o atributo href indica o endereço de destino. O texto entre as tags é o que aparece na página.',words:[['link','ligação / link'],['learn','aprender'],['about me','sobre mim']],instruction:'Escreva uma apresentação curta em inglês no parágrafo. “I am learning” significa “Estou aprendendo”. O link do exemplo leva a uma seção desta página.',code:'<h1>About me</h1>\n<p>I am learning to code.</p>\n<a href="#goal">My goal</a>\n<h2 id="goal">Build a website</h2>',question:'Qual parte do link indica o destino?',answers:['<p>','href','<h1>'],correct:1,feedback:'Correto! href indica para onde o link leva. “My goal” significa “Meu objetivo”.'},
  {topic:'CSS',title:'Dê cor às suas ideias',summary:'Cores e estilos',text:'CSS define a aparência da página. Dentro de <style>, o seletor h1 escolhe o título. A propriedade color muda a cor do texto e background-color muda a cor do fundo.',words:[['color','cor'],['background','fundo'],['blue','azul']],instruction:'Mude color: blue para color: green. Green significa verde. Execute e observe o título.',code:'<style>\n  h1 { color: blue; }\n  p { background-color: lightyellow; }\n</style>\n<h1>My colorful website</h1>\n<p>I like blue.</p>',question:'Qual propriedade muda a cor do texto?',answers:['background-color','color','href'],correct:1,feedback:'Isso! color muda a cor do texto. Background significa fundo.'},
  {topic:'CSS',title:'Espaço para aprender',summary:'Tamanho e espaçamento',text:'font-size define o tamanho do texto. padding cria espaço entre o conteúdo e a borda do elemento. border define uma borda. Aqui, px é uma unidade de medida.',words:[['size','tamanho'],['border','borda'],['space','espaço']],instruction:'Mude padding de 16px para 32px e veja o espaço crescer. Depois, experimente outro tamanho de fonte.',code:'<style>\n  p {\n    font-size: 20px;\n    padding: 16px;\n    border: 2px solid teal;\n  }\n</style>\n<p>Learning takes practice.</p>',question:'O que padding altera?',answers:['O destino de um link','O idioma da página','O espaço interno do elemento'],correct:2,feedback:'Correto! padding cria espaço interno. “Learning takes practice” significa “Aprender exige prática”.'},
  {topic:'JavaScript',title:'Um clique, uma ação',summary:'Botões e eventos',text:'JavaScript permite responder às ações da pessoa. querySelector encontra um elemento. addEventListener registra o que deve acontecer em um evento, como click. textContent muda o texto.',words:[['click','clicar / clique'],['button','botão'],['welcome','bem-vindo(a)']],instruction:'Execute o exemplo e clique em “Say hello”. Depois, troque a mensagem “Welcome!” por “Hello, friend!”.',code:'<button id="hello">Say hello</button>\n<p id="message">Click the button.</p>\n<script>\n  document.querySelector("#hello")\n    .addEventListener("click", () => {\n      document.querySelector("#message").textContent = "Welcome!";\n    });\n<\/script>',question:'Qual evento representa um clique?',answers:['click','color','padding'],correct:0,feedback:'Isso! click é o evento de clique. “Say hello” significa “Diga olá”.'},
  {topic:'JavaScript',title:'Conte suas conquistas',summary:'Variáveis e um miniprojeto',text:'Uma variável guarda um valor. let permite alterar esse valor. Na expressão count = count + 1, o contador recebe seu valor atual mais um. Vamos unir HTML, CSS e JavaScript.',words:[['count','contar / contagem'],['add','adicionar'],['practice','prática / praticar']],instruction:'Execute e clique em “Add one” para aumentar o contador. Personalize as cores e o texto para finalizar seu miniprojeto.',code:'<style>\n  body { font-family: sans-serif; padding: 16px; }\n  button { background: teal; color: white; padding: 12px; border: 0; }\n</style>\n<h1>Practice counter</h1>\n<p id="total">0</p>\n<button id="add">Add one</button>\n<script>\n  let count = 0;\n  document.querySelector("#add").addEventListener("click", () => {\n    count = count + 1;\n    document.querySelector("#total").textContent = count;\n  });\n<\/script>',question:'Se count vale 2, quanto valerá após count = count + 1?',answers:['1','3','2'],correct:1,feedback:'Muito bem! O contador passa a valer 3. “Add one” significa “Adicione um”.'}
].map((lesson, index) => ({
  ...lesson, id: lessonIds[index],
  title: ['Títulos e parágrafos','Links em HTML','Cores com CSS','Fontes e espaçamento','Eventos de clique','Variáveis e contadores'][index],
  wrongFeedback: [
    ['', '“Meu primeiro site” seria “My first website”. Hello significa olá e world significa mundo.', '“Até amanhã” seria “See you tomorrow”. Hello é uma saudação e world significa mundo.'],
    ['A tag <p> cria um parágrafo. O destino de um link é definido pelo atributo href.', '', 'A tag <h1> cria o título principal. Para indicar o destino do link, usamos href.'],
    ['background-color muda a cor do fundo. Para mudar a cor do texto, use color.', '', 'href indica o destino de um link em HTML. A cor do texto é definida por color no CSS.'],
    ['O destino de um link é definido por href. padding cria espaço dentro do elemento.', 'padding não muda o idioma. Ele aumenta ou diminui o espaço entre o conteúdo e a borda.', ''],
    ['', 'color é uma propriedade CSS que muda a cor do texto. O evento de clique chama-se click.', 'padding é uma propriedade CSS de espaçamento. Para responder a um clique, usamos o evento click.'],
    ['O valor inicial é 2. Somar 1 produz 3, e esse resultado é atribuído à variável count.', '', 'A atribuição altera o valor: count recebe 2 + 1, portanto passa a valer 3.'],
  ][index],
}));
const topics=['HTML','CSS','JavaScript','Python','Java','C#'];
const javascriptOrder=['js-values','js-conditions','js-arrays','js-loops','js-events','js-counter'];
const descriptivePatterns={
 'html-semantic':['\\bheader\\b(?:(?!\\bfooter\\b).){0,70}(cabecalho|inicio|topo)','\\bfooter\\b(?:(?!\\bheader\\b).){0,70}(rodape|fim|final)'],
 'css-responsive':['\\b600\\b','(ate|menor|igual|no maximo)[^.;]{0,30}\\b600\\b'],
 'python-functions':['\\bprint\\b(?:(?!\\breturn\\b).){0,60}(mostra|imprime|exibe|escreve)','\\breturn\\b(?:(?!\\bprint\\b).){0,60}(devolve|retorna)'],
 'java-methods':['\\bint\\b(?:(?!\\bvoid\\b).){0,60}(inteiro|integer)','\\bvoid\\b.{0,40}(nao|sem).{0,40}(valor|retorno|retorna|devolve)'],
 'csharp-functions':['\\bconsole\\.writeline\\b(?:(?!\\breturn\\b).){0,60}(mostra|imprime|exibe|escreve)','\\breturn\\b(?:(?!\\bconsole\\b).){0,60}(devolve|retorna)'],
};
export const lessons=topics.flatMap(topic=>{
 const rows=[...baseLessons,...additionalLessons].filter(item=>item.topic===topic);
 if(topic==='JavaScript')rows.sort((a,b)=>javascriptOrder.indexOf(a.id)-javascriptOrder.indexOf(b.id));
 return rows.map((item,index)=>({...item,criteria:item.criteria?.map((criterion,i)=>({...criterion,...(descriptivePatterns[item.id]?.[i]?{pattern:descriptivePatterns[item.id][i]}:{})})),kind:item.kind||'multiple',level:index<2?'Fundamentos':index<4?'Aplicação':'Desafio',filename:item.filename||'index.html'}));
});

